# Generated by Django 5.0.4 on 2024-06-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.IntegerField(null=True)),
                ('product_description', models.TextField()),
                ('product_images', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
